name: Dependency Graph
on: [pull_request]
jobs:
  Dependency-Submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'zulu'
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4